ranks = [{
		tierName: "BEGINNER",
		tier: 1,
		subTier: 5,
		imgText: "beginner-5",
		rpRange: "1-199"
	}, {
		tierName: "BEGINNER",
		tier: 1,
		subTier: 4,
		imgText: "beginner-4",
		rpRange: "200-399",
		rewardCoupon: 1
	}, {
		tierName: "BEGINNER",
		tier: 1,
		subTier: 3,
		imgText: "beginner-3",
		rpRange: "400-599",
		rewardCoupon: 1
	}, {
		tierName: "BEGINNER",
		tier: 1,
		subTier: 2,
		imgText: "beginner-2",
		rpRange: "600-799",
		rewardCoupon: 1
	}, {
		tierName: "BEGINNER",
		tier: 1,
		subTier: 1,
		imgText: "beginner-1",
		rpRange: "800-999",
		rewardCoupon: 1
	}, {
		tierName: "NOVICE",
		tier: 2,
		subTier: 5,
		imgText: "novice-5",
		rpRange: "1000-1199",
		rewardCoupon: 2
	}, {
		tierName: "NOVICE",
		tier: 2,
		subTier: 4,
		imgText: "novice-4",
		rpRange: "1200-1399",
		rewardCoupon: 1
	}, {
		tierName: "NOVICE",
		tier: 2,
		subTier: 3,
		imgText: "novice-3",
		rpRange: "1400-1599",
		rewardCoupon: 1
	}, {
		tierName: "NOVICE",
		tier: 2,
		subTier: 2,
		imgText: "novice-2",
		rpRange: "1600-1799",
		rewardCoupon: 1
	}, {
		tierName: "NOVICE",
		tier: 2,
		subTier: 1,
		imgText: "novice-1",
		rpRange: "1800-1999",
		rewardCoupon: 1
	}, {
		tierName: "EXPERIENCED",
		tier: 3,
		subTier: 5,
		imgText: "experienced-5",
		rpRange: "2000-2199",
		rewardCoupon: 2
	}, {
		tierName: "EXPERIENCED",
		tier: 3,
		subTier: 4,
		imgText: "experienced-4",
		rpRange: "2200-2399",
		rewardCoupon: 1
	}, {
		tierName: "EXPERIENCED",
		tier: 3,
		subTier: 3,
		imgText: "experienced-3",
		rpRange: "2400-2599",
		rewardCoupon: 1
	}, {
		tierName: "EXPERIENCED",
		tier: 3,
		subTier: 2,
		imgText: "experienced-2",
		rpRange: "2600-2799",
		rewardCoupon: 1
	}, {
		tierName: "EXPERIENCED",
		tier: 3,
		subTier: 1,
		imgText: "experienced-1",
		rpRange: "2800-2999",
		rewardCoupon: 1
	}, {
		tierName: "SKILLED",
		tier: 4,
		subTier: 5,
		imgText: "skilled-5",
		rpRange: "3000-3199",
		rewardCoupon: 2
	}, {
		tierName: "SKILLED",
		tier: 4,
		subTier: 4,
		imgText: "skilled-4",
		rpRange: "3200-3399",
		rewardCoupon: 1
	}, {
		tierName: "SKILLED",
		tier: 4,
		subTier: 3,
		imgText: "skilled-3",
		rpRange: "3400-3599",
		rewardCoupon: 1
	}, {
		tierName: "SKILLED",
		tier: 4,
		subTier: 2,
		imgText: "skilled-2",
		rpRange: "3600-3799",
		rewardCoupon: 1
	}, {
		tierName: "SKILLED",
		tier: 4,
		subTier: 1,
		imgText: "skilled-1",
		rpRange: "3800-3999",
		rewardCoupon: 1
	}, {
		tierName: "SPECIALIST",
		tier: 5,
		subTier: 5,
		imgText: "specialist-5",
		rpRange: "4000-4199",
		rewardCoupon: 2
	}, {
		tierName: "SPECIALIST",
		tier: 5,
		subTier: 4,
		imgText: "specialist-4",
		rpRange: "4200-4399",
		rewardCoupon: 1
	}, {
		tierName: "SPECIALIST",
		tier: 5,
		subTier: 3,
		imgText: "specialist-3",
		rpRange: "4400-4599",
		rewardCoupon: 1
	}, {
		tierName: "SPECIALIST",
		tier: 5,
		subTier: 2,
		imgText: "specialist-2",
		rpRange: "4600-4799",
		rewardCoupon: 1
	}, {
		tierName: "SPECIALIST",
		tier: 5,
		subTier: 1,
		imgText: "specialist-1",
		rpRange: "4800-4999",
		rewardCoupon: 1
	}, {
		tierName: "EXPERT",
		tier: 6,
		subTier: 0,
		imgText: "expert",
		rpRange: "5000-5999",
		rewardCoupon: 3
	}, {
		tierName: "SURVIVOR",
		tier: 7,
		subTier: 0,
		imgText: "survivor",
		rpRange: "6000-",
		rewardCoupon: 4
	}
]
var links = '';
for(var i=0;i<rank.length;i++){
	var imgText = rank[i].imgText;
	links += `<span class="link">https://prod-live-front.playbattlegrounds.com/app/pc-1903-2019.03.28-6909/assets/images/rank/emblem-${imgText}.png"`;
};
$('.result').html(links);