var PUBGITEMS = 
    [{
      "item": "utilitybelt",
      "name": "Utility Belt",
      "i18name": "UtilityBelt",
      "icon": "belt",
      "capacity": "+50",
      "desc": "The Utility Belt is a belt inventory item that increases inventory space.",
      "i18desc": "UtilityBeltDesc"
    },
     {
       "item":"backpack1",
       "name": "Backpack (Level 1)",
       "i18name": "Backpack",
       "icon": "backpack1a",
       "icon2": "backpack1b",
       "capacity": "+150",
       "desc": "The Backpack (Lv.1) is a storage piece of equipment that allows for a light amount of item storage, increasing your inventory.",
       "i18desc": "BackpackLv1Desc"},
     {
       "item":"backpack2",
       "name": "Backpack (Level 2)",
       "i18name": "Backpack2",
       "icon": "backpack2a",
       "icon2": "backpack2b",
       "capacity": "+200",
       "desc": "The Backpack (Lv.2) is a storage piece of equipment that allows for a medium amount of item storage, increasing your inventory.",
       "i18desc": "BackpackLv2Desc"},
     {
       "item":"backpack3",
       "name": "Backpack (Level 3)",
       "i18name": "Backpack3",
       "icon": "backpack3a",
       "icon2": "backpack3b",
       "capacity": "+250",
       "desc": "The Backpack (Lv.3) is a storage piece of equipment that allows for a significant amount of item storage, increasing your inventory by +250 capacity.",
       "i18desc": "BackpackLv3Desc"},
     {
       "item":"helmet1",
       "name": "Motorcycle Helmet (Level 1)",
       "i18name": "Helmet1",
       "icon": "helmet1a",
       "icon2": "helmet1b",
	   "icontext": "green",
	   "icontexti18": "green",
	   "icontext2": "grey",
	   "icontext2i18": "grey",
       "type": "Durability",
       "i18type": "Durability",
       "amount": "80",
	   "dmgtext": "Damage Reduction",
       "dmgtexti18": "DamageReduction",
	   "dmgreduction": "30%",
       "desc": ""},
     {
       "item":"helmet2",
       "name": "Military Helmet (Level 2)",
       "i18name": "Helmet2",
       "icon": "helmet2a",
       "icon2": "helmet2b",
	   "icontext": "desert camo",
	   "icontexti18": "desertcamo",
	   "icontext2": "woodland camo",
	   "icontext2i18": "woodlandcamo",
       "type": "Durability",
       "i18type": "Durability",
       "amount": "150",
       "dmgtext": "Damage Reduction",
       "dmgtexti18": "DamageReduction",
	   "dmgreduction": "40%",
       "desc": ""},
     {
       "item":"helmet3",
       "name": "Spetsnaz Helmet (Level 3)",
       "i18name": "Helmet3",
       "icon": "helmet3a",
       "type": "Durability",
       "i18type": "Durability",
       "amount": "230",
       "dmgtext": "Damage Reduction",
       "dmgtexti18": "DamageReduction",
	   "dmgreduction": "55%",
       "desc": ""},
     {
       "item":"vest1",
       "name": "Police Vest (Level 1)",
       "i18name": "PoliceVest1",
       "icon": "vest1",
       "type": "Durability",
       "i18type": "Durability",
       "amount": "200",
	   "dmgtext": "Damage Reduction",
       "dmgtexti18": "DamageReduction",
	   "dmgreduction": "30%",
       "capacity": "+50",
       "desc": ""},
     {
       "item":"vest2",
       "name": "Police Vest (Level 2)",
       "i18name": "PoliceVest2",
       "icon": "vest2",
       "type": "Durability",
       "i18type": "Durability",
       "amount": "220",
	   "dmgtext": "Damage Reduction",
       "dmgtexti18": "DamageReduction",
	   "dmgreduction": "40%",
       "capacity": "+50",
       "desc": ""},
     {
       "item":"vest3",
       "name": "Military Vest (Level 3)",
       "i18name": "MilitaryVest",
       "icon": "vest3",
       "type": "Durability",
       "i18type": "Durability",
       "amount": "250",
	   "dmgtext": "Damage Reduction",
       "dmgtexti18": "DamageReduction",
	   "dmgreduction": "55%",
       "capacity": "+50",
       "desc": ""},
		// Consumables
     {
       "item":"medkit",
       "name":"MedKit",
       "i18name":"MedKit",
       "icon": "medkit",
       "type": "Heal",
       "i18type": "Heal",
       "amount": "100%",
       "quantity": "1",
       "usetime": "10s",
       "desc": "Med Kits heal a character's health to 100 instantly. Performing certain actions while casting this item will cancel it.",
       "i18desc": "MedKitDesc"},
     {
       "item":"firstaidkit",
       "name": "First Aid Kit",
       "i18name": "FirstAidKit",
       "icon": "firstaidkit",
       "type": "Heal",
       "i18type": "Heal",
       "amount": "75%",
       "quantity": "1",
       "usetime": "7.5s",
       "desc": "First Aid Kits heal a character's health to 75 instantly. Performing certain actions while casting this item will cancel it. This item cannot be used when player's health is over 75.",
       "i18desc": "FirstAidKitDesc"},
     {
       "item":"bandage",
       "name": "Bandage",
       "i18name": "Bandage",
       "icon": "bandage",
       "type": "Heal",
       "i18type": "Heal",
       "amount": "10%",
       "quantity": "5",
       "usetime": "4s",
       "desc": "After certain amount of time, Bandage heals character's health up to 10 overtime. performing certain actions whil casting this item can cancel the effect. Cannot heal character's health over 75.",
       "i18desc": "BandageDesc"},
     {
       "item":"painkiller",
       "name": "Painkiller",
       "i18name": "Painkiller",
       "icon": "painkiller",
       "type": "Boost",
       "i18type": "Boost",
       "amount": "60%",
       "usetime": "7.5",
       "duration": "3",
       "totalHeal": "40%",
       "quantity": "1",
       "bonusbar": "booster-bar",
       "bartype": ["heal","b60"],
       "desc": "Painkillers increase a character's boost by 60 instantly. Performing certain actions while casting this item will cancel it.",
       "i18desc": "PainkillerDesc"},
     {
       "item":"adrenaline",
       "name": "Adrenaline Syringe",
       "i18name": "AdrenalineSyringe",
       "icon": "adrenaline",
       "type": "Boost",
       "i18type": "Boost",
       "amount": "100%",
       "usetime": "10s",
       "duration": "5",
       "totalHeal": "86%",
       "bonusSpeed": "+ 6.2%",
       "quantity": "1",
       "bonusbar": "booster-bar",
       "bartype": ["heal boost","b100"],
       "desc": "Adrenaline Syringes increase a character's boost by 100 instantly. Performing certain actions while casting this item will cancel it."},
	   {
       "item":"gascan",
       "icon": "gascan",
       "name": "Gas Can",
       "i18name": "GasCan",
	   "usetime": "10s",
       "capacity": "20",
       "i18desc": "GasCanDesc",
       "desc": "You can refuel vehicles with it."},
     {
       "item":"energydrink",
       "name": "Energy Drink",
       "i18name": "EnergyDrink",
       "icon": "energydrink",
       "type": "Boost",
       "i18type": "Boost",
       "amount": "40%",
       "usetime": "4",
       "duration": "2",
       "totalHeal": "23%",
       "quantity": "1",
       "bonusbar": "booster-bar",
       "bartype": ["heal","b40"],
       "desc": "Energy Drinks increase a character's boost by 40 instantly. Also it will heal you above the 75% mark over time. Performing certain actions while casting this item will cancel it."},

     // AMMO
     {
       "item":"12Gauge",
       "name": "12 Gauge",
       "i18name": "12Gauge",
       "icon": "ammo12Gauge",
       "ammo": "Ammo for",
       "i18ammo": "Ammofor",
       "ammofor": ["s686", "s1897", "s12k"]},
     {
       "item":"300magnum",
       "name": ".300Magnum",
       "i18name": "300Magnum",
       "icon": "ammo300magnum",
       "ammo": "Ammo for",
       "i18ammo": "Ammofor",
       "ammofor": ["awm"]},
     {
       "item":"45mm",
       "name": ".45 ACP Ammo",
       "i18name": "45acpammo",
       "icon": "ammo45mm",
       "ammo": "Ammo for",
       "i18ammo": "Ammofor",
       "ammofor": ["p1911", "tommygun", "vector"]},
     {
       "item":"556mm",
       "name": "5.56mm",
       "i18name": "556mm",
       "icon": "ammo556mm",
       "ammo": "Ammo for",
       "i18ammo": "Ammofor",
       "ammofor": ["m16a4", "m416", "scar-l"]},
     {
       "item":"762mm",
       "name": "7.62mm",
       "i18name": "762mm",
       "icon": "ammo762mm",
       "ammo": "Ammo for",
       "i18ammo": "Ammofor",
       "ammofor": ["akm", "kar98", "m24", "r1895", "sks"]},
     {
       "item":"9mm",
       "name": ".9mm",
       "i18name": "9mm",
       "icon": "ammo9mm",
       "ammo": "Ammo for",
       "i18ammo": "Ammofor",
       "ammofor": ["microuzi", "p92", "ump9","vss"]},
     {
       "item":"bolt",
       "name": "bolt",
       "i18name": "bolt",
       "icon": "ammobolt",
       "ammo": "Ammo for",
       "i18ammo": "Ammofor",
       "ammofor": ["crossbow"]},
     // Trowables
     {
       "item":"frag",
       "icon": "frag",
       "name": "Frag Grenade",
       "i18name": "FragGrenade",
       "capacity": "12",
       "i18desc": "FragDesc",
       "desc": "Fire in the hole"},
     {
       "item":"molotov",
       "icon": "molotov",
       "name": "Molotov",
       "i18name": "Molotov",
       "capacity": "18",
       "i18desc": "MolotovDesc",
       "desc": "Higly explosive. Do not drink."},
     {
       "item":"smoke",
       "icon": "smoke",
       "name": "Smoke Grenade",
       "i18name": "SmokeBomb",
       "capacity": "16",
       "i18desc": "SmokeBombDesc",
       "desc": "Smokin' useful"},
     {
       "item":"stun",
       "icon": "stun",
       "name": "Stun Grenade",
       "capacity": "14",
       "i18name": "StunGrenade",
       "i18desc": "StunGrenadeDesc",
       "desc": "Disorient a player for 10 seconds"},
     // Melee
     {
       "item":"crowbar",
       "icon": "crowbar",
       "name": "Crowbar",
       "i18name": "Crowbar",
	   "damage": "60",
	   "desc": "A faithful shooter for every situation.",
	   "i18desc": "CrowbarDesc"},
     {
       "item":"machete",
       "icon": "machete",
       "name": "Machete",
       "i18name": "Machete",
	   "damage": "60",
	   "desc": "Typical weapon for slaughter.",
	   "i18desc": "MacheteDesc"},
     {
       "item":"pan",
       "icon": "pan",
       "name": "Pan",
       "i18name": "Pan",
	   "damage": "80",
	   "desc": "Not for cooking",
	   "i18desc": "PanDesc"},
     {
       "item":"sickle",
       "icon": "sickle",
       "name": "Sickle",
       "i18name": "Sickle",
	   "damage": "60",
	   "desc": "Good for shaving.",
	   "i18desc": "SickleDesc"},
     {
       "item":"awm",
       "name": "AWM",
       "type":"Sniper Rifle",
       "typei18":"SniperRifle",
       "ammo": ".300 Magnum",
       "ammoIcon": "300magnum",
       "desc": "Monster sniper rifle.",
       "i18desc": "awm-desc.",
       "slots": ["muzzle","none","mag","stock"],
       "capacity": "5",
       "power": "100",
       "range":"100",
       "stability": "23",
       "rate": "6",
       "attachs": ["supressorsniper","compensatorawm","flashhiderawm","quickdrawawm","extendedmagawm","extendedquickdrawawm","cheekpadawm"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"m24",
       "name": "M24",
       "type":"Sniper Rifle",
       "typei18":"SniperRifle",
       "ammo": "7.62mm",
       "ammoIcon": "762mm",
       "desc": "Serviceable sniper rifle.",
       "i18desc": "m24-desc.",
       "slots": ["muzzle","none","mag","stock"],
       "capacity": "5",
       "power": "77",
       "range":"96",
       "stability": "32",
       "rate": "6",
       "attachs": ["supressorsniper","compensatorm24","flashhiderm24","quickdrawm24","extendedmagm24","extendedquickdrawm24","cheekpadm24"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"kar98",
       "name": "Kar98K",
       "type":"Sniper Rifle",
       "typei18":"SniperRifle",
       "ammo": "7.62mm",
       "ammoIcon": "762mm",
       "desc": "Vintage sniper rifle.",
       "i18desc": "kar98-desc.",
       "slots": ["muzzle","none","none","stock"],
       "capacity": "5",
       "power": "66",
       "range":"79",
       "stability": "34",
       "rate": "4",
       "attachs": ["supressorsniper","compensatorkar98k","flashhiderkar98k","cheekpadkar98k","bulletloopskar98k"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"sks",
       "name": "SKS",
       "type":"Sniper Rifle",
       "typei18":"SniperRifle",
       "ammo": "7.62mm",
       "ammoIcon": "762mm",
       "desc": "Semi-auto Russian DMR rifle.",
       "i18desc": "awm-desc.",
       "slots": ["muzzle","none","mag","stock"],
       "capacity": "10",
       "power": "50",
       "range":"64",
       "stability": "45",
       "rate": "31",
       "attachs": ["supressorsniper","compensatorsks","flashhidersks","quickdrawsks","extendedmagsks","extendedquickdrawsks","cheekpadsks"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"vss",
       "name": "VSS",
       "type":"Sniper Rifle",
       "typei18":"SniperRifle",
       "ammo": "9mm",
       "ammoIcon": "9mm",
       "desc": "The VSS is a supressed sniper rifle that uses a heavy subsonic 9mm cartridge.",
       "i18desc": "vss-desc.",
       "slots": ["none","none","mag","stock"],
       "capacity": "10",
       "power": "32",
       "range":"38",
       "stability": "16",
       "rate": "22",
       "attachs": ["quickdrawvss","extendedmagvss","extendedquickdrawvss","cheekpadvss"]},
     {
       "item":"akm",
       "name": "AKM",
       "type":"Assault Rifle",
       "typei18":"AssaultRifle",
       "ammo": "7.62mm",
       "ammoIcon": "762mm",
       "desc": "For comrades-in-arms.",
       "i18desc": "akm-desc.",
       "slots": ["muzzle","none","mag","none"],
       "capacity": "30",
       "power": "44",
       "range":"59",
       "stability": "34",
       "rate": "61",
       "attachs": ["supressorar","compensatorakm","flashhiderakm","quickdrawakm","extendedmagakm","extendedquickdrawakm"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"scar-l",
       "name": "SCAR-L",
       "type":"Assault Rifle",
       "typei18":"AssaultRifle",
       "ammo": "5.56mm",
       "ammoIcon": "556mm",
       "desc": "Modern assault rifle.",
       "i18desc": "scar-l-desc.",
       "slots": ["muzzle","grip","mag","none"],
       "capacity": "30",
       "power": "37",
       "range":"55",
       "stability": "31",
       "rate": "71",
       "attachs": ["supressorar","compensatorscar","flashhiderscar","angledforegripscar","verticalforegripscar","quickdrawscar","extendedmagscar","extendedquickdrawscar"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"m16a4",
       "name": "M16A4",
       "type":"Assault Rifle",
       "typei18":"AssaultRifle",
       "ammo": "5.56mm",
       "ammoIcon": "556mm",
       "desc": "Burstfire assault rifle.",
       "i18desc": "m16a4-desc.",
       "slots": ["muzzle","none","mag","none"],
       "capacity": "30",
       "power": "37",
       "range":"62",
       "stability": "28",
       "rate": "81",
       "attachs": ["supressorar","compensatorm16a4","flashhiderm16a4","quickdrawm16a4","extendedmagm16a4","extendedquickdrawm16a4"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"m416",
       "name": "M416",
       "type":"Assault Rifle",
       "typei18":"AssaultRifle",
       "ammo": "5.56mm",
       "ammoIcon": "556mm",
       "desc": "German do things properly.",
       "i18desc": "m416-desc.",
       "slots": ["muzzle","grip","mag","stock"],
       "capacity": "30",
       "power": "37",
       "range":"57",
       "stability": "32",
       "rate": "77",
       "attachs": ["supressorar","compensatorm416","flashhiderm416","angledforegripm416","verticalforegripm416","quickdrawm416","extendedmagm416","extendedquickdrawm416","tacticalstockm416"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
	   {
       "item":"groza",
       "name": "Groza",
       "type":"Assault Rifle",
       "typei18":"AssaultRifle",
       "ammo": "7.62mm",
       "ammoIcon": "762mm",
       "desc": "A selective fire Russian bullpup assault rifle chambered for a 7.62mm round.",
       "i18desc": "groza-desc.",
       "slots": ["muzzle","none","mag","none"],
       "capacity": "30",
       "power": "44",
       "range":"60",
       "stability": "22",
       "rate": "67",
       "attachs": ["supressorar","compensatorgroza","flashhidergroza","quickdrawgroza","extendedmaggroza","extendedquickdrawgroza"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"m249",
       "name": "M249",
       "type":"Light Machinegun",
       "typei18":"LightMachinegun",
       "ammo": "5.56mm",
       "ammoIcon": "556mm",
       "desc": "Lighter than it looks.",
       "i18desc": "m249-desc.",
       "slots": ["none","none","none","none"],
       "capacity": "100",
       "power": "40",
       "range":"71",
       "stability": "44",
       "rate": "77",
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"tommygun",
       "name": "Tommy Gun",
       "type":"Sub Machinegun",
       "typei18":"SubMachinegun",
       "ammo": ".45 ACP",
       "ammoIcon": "45acp",
       "desc": "Infinite ammo with trech coat on.",
       "i18desc": "tommygun-desc.",
       "slots": ["none","none","none","none"],
       "capacity": "100",
       "power": "35",
       "range":"46",
       "stability": "31",
       "rate": "100"},
     {
       "item":"ump9",
       "name": "UMP9",
       "type":"Sub Machinegun",
       "typei18":"SubMachinegun",
       "ammo": "9mm",
       "ammoIcon": "9mm",
       "desc": "Modern submachine gun using 9mm ammonition.",
       "i18desc": "ump9-desc.",
       "slots": ["muzzle","grip","mag","none"],
       "capacity": "30",
       "power": "30",
       "range":"30",
       "stability": "31",
       "rate": "62",
       "attachs": ["supressorsmg","compensatorump9","flashhiderump9","angledforegripump9","verticalforegripump9","quickdrawump9","extendedmagump9","extendedquickdrawump9"],
       "attsights": ["reddot","holographic","scope2x","scope4x"]},
     {
       "item":"microuzi",
       "name": "Micro Uzi",
       "type":"Sub Machinegun",
       "typei18":"SubMachinegun",
       "ammo": "9mm",
       "ammoIcon": "9mm",
       "desc": "Spray your ammo but beware to not shoot yourself in the foot.",
       "i18desc": "microuzi-desc.",
       "slots": ["muzzle","none","mag","stock"],
       "capacity": "25",
       "power": "21",
       "range":"22",
       "stability": "31",
       "rate": "70",
       "attachs": ["supressorsmg","compensatormicrouzi","flashhidermicrouzi","quickdrawmicrouzi","extendedmagmicrouzi","extendedquickdrawmicrouzi"]},
     {
       "item":"vector",
       "name": "KRISS Vector",
       "type":"Sub Machinegun",
       "typei18":"SubMachinegun",
       "ammo": ".45",
       "ammoIcon": "45acp",
       "desc": "Modern SMG using delayed blowback system and chambered .45 ACP ammonition.",
       "i18desc": "vector-desc.",
       "slots": ["muzzle","grip","mag","stock"],
       "capacity": "13",
       "power": "28",
       "range":"20",
       "stability": "29",
       "rate": "54",
       "attachs": ["supressorsmg","compensatorvector","flashhidervector","verticalforegripvector","quickdrawvector","extendedmagvector","extendedquickdrawvector","tacticalstockvector"],
       "attsights": ["reddot","holographic","scope2x","scope4x"],
       "verified": ""},
     {
       "item":"s686",
       "name": "S686",
       "type":"Shotgun",
       "typei18":"Shotgun",
       "ammo": "12 Gauge",
       "ammoIcon": "12gauge",
       "desc": "Double barrel shotgun.",
       "i18desc": "s686-desc.",
       "slots": ["muzzle","none","none","stock"],
       "capacity": "2",
       "power": "100",
       "range":"13",
       "stability": "77",
       "rate": "7",
       "attachs": ["choke","bulletloopsS686"]},
     {
       "item":"s1897",
       "name": "S1897",
       "type":"Shotgun",
       "typei18":"Shotgun",
       "ammo": "12 Gauge",
       "ammoIcon": "12gauge",
       "desc": "Modest shotgun.",
       "i18desc": "s1897-desc.",
       "slots": ["muzzle","none","none","stock"],
       "capacity": "5",
       "power": "100",
       "range":"8",
       "stability": "77",
       "rate": "8",
       "attachs": ["choke","bulletloopsS1897"]},
     {
       "item":"s12k",
       "name": "S12K",
       "type":"Shotgun",
       "typei18":"Shotgun",
       "ammo": "12 Gauge",
       "ammoIcon": "12gauge",
       "desc": "Kinda foul in this world.",
       "i18desc": "s12k-desc.",
       "slots": ["muzzle","none","mag","none"],
       "capacity": "5",
       "power": "92",
       "range":"9",
       "stability": "86",
       "rate": "15",
       "attachs": ["supressorar","compensators12k","flashhiders12k","quickdraws12k","extendedmags12k","extendedquickdraws12k"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
     {
       "item":"r1895",
       "name": "R1895",
       "type":"Handgun",
       "typei18":"Handgun",
       "ammo": "7.62mm",
       "ammoIcon": "762mm",
       "desc": "Powerful revolver using 7.62mm ammonition.",
       "i18desc": "r1895-desc.",
       "slots": ["muzzle","none","none","none"],
       "capacity": "7",
       "power": "42",
       "range":"31",
       "stability": "29",
       "rate": "11",
       "attachs": ["supressorpistol"]},
     {
       "item":"p1911",
       "name": "P1911",
       "type":"Handgun",
       "typei18":"Handgun",
       "ammo": ".45 ACP",
       "ammoIcon": "45acp",
       "desc": "Your grandpa loved it.",
       "i18desc": "p1911-desc.",
       "slots": ["muzzle","none","mag","none"],
       "capacity": "7",
       "power": "32",
       "range":"15",
       "stability": "26",
       "rate": "29",
       "attachs": ["supressorpistol","quickdrawP1911","extendedmagP1911","extendedquickdrawP1911"],
	   "attsights": ["reddot"]},
     {
       "item":"p92",
       "name": "P92",
       "type":"Handgun",
       "typei18":"Handgun",
       "ammo": "9mm",
       "ammoIcon": "9mm",
       "desc": "Modest handgun.",
       "i18desc": "p92-desc.",
       "slots": ["muzzle","none","mag","none"],
       "capacity": "15",
       "power": "27",
       "range":"15",
       "stability": "25",
       "rate": "53",
       "attachs": ["supressorpistol","quickdrawP92","extendedmagP92","extendedquickdrawP92"],
	   "attsights": ["reddot"]},
	   {
       "item":"p18c",
       "name": "P18C",
       "type": "Handgun",
       "typei18":"Handgun",
       "ammo": "9mm",
       "ammoIcon": "9mm",
       "desc": "An Austrian pistol with a full-auto mode and chambered for a 9mm round.",
       "i18desc": "p18c-desc.",
       "slots": ["muzzle","none","mag","none"],
       "capacity": "17",
       "power": "17",
       "range":"10",
       "stability": "24",
       "rate": "68",
       "attachs": ["supressorpistol","quickdrawP18C","extendedmagP18C","extendedquickdrawP18C"],
	   "attsights": ["reddot"]},
     {
       "item":"crossbow",
       "name": "Crossbow",
       "type":"Crossbow",
       "typei18":"Crossbow",
       "ammo": "bolt",
       "ammoIcon": "bolt",
       "desc": "Hard to use, good to assassinate.",
       "i18desc": "crossbow-desc.",
       "slots": ["none","none","mag","none"],
       "capacity": "15",
       "power": "95",
       "range":"16",
       "stability": "0",
       "rate": "2",
       "attachs": ["quiver"],
       "attsights": ["reddot","holographic","scope2x","scope4x","scope8x","scope15x"]},
	   // Attachments
	   {
        "item":"supressorsniper",
		"icon": "supressorsniper",
        "i18n":"supressorsniper",
        "name":"Suppressor for M24, AWM, SKS, Kar98k",
        "desc": "Reduces a weaponӳ sound to increase stealth",
        "i18desc": "supressor-text",
        "unique": "muzzle",
		"bonus" : ["-5.00%","Deviation"],
        "attweapons": ["m24", "awm", "sks", "kar98"]},
		{
        "item":"compensatorsniper",
        "icon": "compensatorsniper",
        "i18n":"compensatorsniper",
        "name":"Compensator for M24, AWM, SKS, Kar98k",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "unique": "muzzle",
		"bonustype1": "Recoil Pattern",
		"bonus1" : "-25.00%",
		"bonustype1i18": "RecoilPattern",
		"bonustype2": "Horizontal Recoil",
		"bonus2" : "-25.00%",
		"bonustype2i18": "HorizontalRecoil",
		"bonustype3": "Vertical Recoil",
		"bonus3" : "-25.00%",
		"bonustype3i18": "VerticalRecoil",
        "attweapons": ["m24", "awm", "sks", "kar98"]},
		{
        "item":"flashhidersniper",
        "icon": "flashhidersniper",
        "i18n":"flashhidersniper",
        "name":"Flash Hider for M24, AWM, SKS, Kar98k",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "unique": "muzzle",
        "attweapons": ["m24", "awm", "sks", "kar98"]},
		{
        "item":"quickdrawsniper",
        "icon": "quickdrawsniper",
        "i18n":"quickdrawsmg",
        "name":"QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "unique": "mag",
        "attweapons": ["m24", "awm", "sks", "vss"]},
      {
        "item":"extendedmagsniper",
        "icon": "extendedmagsniper",
        "i18n":"extendedmagsniper",
        "name":"Extended Mag for M24, AWM, SKS, VSS",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "unique": "mag",
        "attweapons": ["m24", "awm", "sks", "vss"]},
      {
        "item":"extendedquickdrawsniper",
        "icon": "extendedquickdrawsniper",
        "i18n":"extendedquickdrawsniper",
        "name":"Extended QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "quickdraw-text",
        "unique": "mag",
        "attweapons": ["m24", "awm", "sks", "vss"]},
      {
        "item":"cheekpadsniper",
        "icon": "cheekpadsniper",
        "i18n": "cheekpadsniper",
        "name": "Cheek Pad for Sniper Rifle",
        "desc": "Reduces recoil kick and sway",
        "i18desc": "cheekpadsniper-text",
        "unique": "stock",
        "attweapons": ["m24", "awm", "sks", "vss", "kar98"]},
		{
        "item":"bulletloopskar98",
        "icon": "bulletloopssniper",
        "i18n":"bulletloops",
        "name":"Bullet Loops for Kar98k",
        "desc": "Increases reload speed",
        "i18desc": "bulletloops-text",
        "unique": "stock",
        "attweapons": ["kar98"]},
		// Crates
		{
        "item":"crate",
        "icon": "crate",
        "i18n":"pioneercrate",
        "name":"Pioneer Crate"},
		{
        "item":"crate1",
        "icon": "crate",
        "i18n":"pioneercrate",
        "name":"Pioneer Crate",
        "number": "#1",
        "bp": "700"},
		{
        "item":"crate2",
        "icon": "crate",
        "i18n":"pioneercrate",
        "name":"Pioneer Crate",
        "number": "#2",
        "bp": "1400"},
		{
        "item":"crate3",
        "icon": "crate",
        "i18n":"pioneercrate",
        "name":"Pioneer Crate",
        "number": "#3",
        "bp": "2800"},
		{
        "item":"crate4",
        "icon": "crate",
        "i18n":"pioneercrate",
        "name":"Pioneer Crate",
        "number": "#4",
        "bp": "4200"},
		{
        "item":"crate5",
        "icon": "crate",
        "i18n":"pioneercrate",
        "name":"Pioneer Crate",
        "number": "#5",
        "bp": "5600"},
		{
        "item":"crate6",
        "icon": "crate",
        "i18n":"pioneercrate",
        "name":"Pioneer Crate",
        "number": "#6",
        "bp": "7000"},
		{
        "item":"preordercrate",
        "icon": "preordercrate",
        "i18n":"PreOrderCrate",
        "name":"PreOrderCrate"},
		{
        "item":"twitchprimebox",
        "icon": "twitchprimebox",
        "i18n":"TwitchCrate",
        "name":"Twitch Prime Box Crate"},
		// Vehicles
		{
      "item":"motorbike",
      "name": "Motorbike",
      "seats": "3",
      "health": "1025",
      "maxspeed": "135"},
     {
       "item":"dirtbike",
       "name": "Dirtbike",
       "seats": "2",
       "health": "1025",
       "maxspeed": "152"},
     {
       "item":"buggy",
       "name": "Buggy",
       "seats": "2",
       "health": "1540",
       "maxspeed": "90"},
     {
       "item":"dacia",
       "name": "Dacia",
       "seats": "4",
       "health": "1820",
       "maxspeed": "117"},
     {
       "item":"uaz",
       "name": "UAZ",
       "seats": "5",
       "health": "1820",
       "maxspeed": "95"},
     {
       "item":"jeep",
       "name": "Jeep",
       "seats": "5",
       "health": "1820",
       "maxspeed": "95"},
     {
       "item":"boat",
       "name": "Jeep",
       "seats": "6",
       "health": "1520",
       "maxspeed": "90"},
    ];

var ATTACHMENTS = 
    [
      {
        "attachment":"supressorsniper",
		"icon": "supressorsniper",
        "icon": "supressorsniper",
        "i18n":"supressorsniper",
        "name":"Suppressor for M24, AWM, SKS, Kar98k",
        "desc": "Reduces a weaponӳ sound to increase stealth",
        "i18desc": "supressor-text",
        "unique": "muzzle",
        "verified": "?"},
      // AWM
      {
        "attachment":"compensatorawm",
        "icon": "compensatorsniper",
        "i18n":"compensatorsniper",
        "name":"Compensator for M24, AWM, SKS, Kar98k",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "3",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"flashhiderawm",
        "icon": "flashhidersniper",
        "i18n":"flashhidersniper",
        "name":"Flash Hider for M24, AWM, SKS, Kar98k",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"quickdrawawm",
        "icon": "quickdrawsniper",
        "i18n":"quickdrawsmg",
        "name":"QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "1",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedmagawm",
        "icon": "extendedmagsniper",
        "i18n":"extendedmagsniper",
        "name":"Extended Mag for M24, AWM, SKS, VSS",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "1",
        "capacity": "7",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawawm",
        "icon": "extendedquickdrawsniper",
        "i18n":"extendedquickdrawsniper",
        "name":"Extended QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "1",
        "capacity": "7",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"cheekpadawm",
        "icon": "cheekpadsniper",
        "i18n": "cheekpadsniper",
        "name": "Cheek Pad for Sniper Rifle",
        "desc": "Reduces recoil kick and sway",
        "i18desc": "cheekpadsniper-text",
        "bonus": "stability",
        "value": "11",
        "unique": "stock",
        "verified": "?"},
      // M24
      {
        "attachment":"compensatorm24",
        "icon": "compensatorsniper",
        "i18n":"compensatorsniper",
        "name":"Compensator for M24, AWM, SKS, Kar98k",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "3",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhiderm24",
        "icon": "flashhidersniper",
        "i18n":"flashhidersniper",
        "name":"Flash Hider for M24, AWM, SKS, Kar98k",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"quickdrawm24",
        "icon": "quickdrawsniper",
        "i18n":"quickdrawsmg",
        "name":"QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "1",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedmagm24",
        "icon": "extendedmagsniper",
        "i18n":"extendedmagsniper",
        "name":"Extended Mag for M24, AWM, SKS, VSS",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "20",
        "capacity": "7",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawm24",
        "icon": "extendedquickdrawsniper",
        "i18n":"extendedquickdrawsniper",
        "name":"Extended QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "1",
        "capacity": "7",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"cheekpadm24",
        "icon": "cheekpadsniper",
        "i18n": "cheekpadsniper",
        "name": "Cheek Pad for Sniper Rifle",
        "desc": "Reduces recoil kick and sway",
        "i18desc": "cheekpadsniper-text",
        "bonus": "stability",
        "value": "11",
        "unique": "stock",
        "verified": ""},
      // Kar98k
      {
        "attachment":"compensatorkar98k",
        "icon": "compensatorsniper",
        "i18n":"compensatorsniper",
        "name":"Compensator for M24, AWM, SKS, Kar98k",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"flashhiderkar98k",
        "icon": "flashhidersniper",
        "i18n":"flashhidersniper",
        "name":"Flash Hider for M24, AWM, SKS, Kar98k",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"cheekpadkar98k",
        "icon": "cheekpadsniper",
        "i18n": "cheekpadsniper",
        "name": "Cheek Pad for Sniper Rifle",
        "desc": "Reduces recoil kick and sway",
        "i18desc": "cheekpadsniper-text",
        "bonus": "stability",
        "value": "9",
        "unique": "stock",
        "verified": "?"},
      {
        "attachment":"bulletloopskar98k",
        "icon": "bulletloopssniper",
        "i18n":"bulletloops",
        "name":"Bullet Loops for Kar98k",
        "desc": "Increases reload speed",
        "i18desc": "bulletloops-text",
        "bonus": "rate",
        "value": "1",
        "unique": "stock",
        "verified": "?"},
      // SKS
      {
        "attachment":"compensatorsks",
        "icon": "compensatorsniper",
        "i18n":"compensatorsniper",
        "name":"Compensator for M24, AWM, SKS, Kar98k",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "3",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhidersks",
        "icon": "flashhidersniper",
        "i18n":"flashhidersniper",
        "name":"Flash Hider for M24, AWM, SKS, Kar98k",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"quickdrawsks",
        "icon": "quickdrawsniper",
        "i18n":"quickdrawsniper",
        "name":"QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "1",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedmagsks",
        "icon": "extendedmagsniper",
        "i18n":"extendedmagsniper",
        "name":"Extended Mag for M24, AWM, SKS, VSS",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "20",
        "capacity": "20",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawsks",
        "icon": "extendedquickdrawsniper",
        "i18n":"extendedquickdrawsniper",
        "name":"Extended QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "28",
        "capacity": "20",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"cheekpadsks",
        "icon": "cheekpadsniper",
        "i18n": "cheekpadsniper",
        "name": "Cheek Pad for Sniper Rifle",
        "desc": "Reduces recoil kick and sway",
        "i18desc": "cheekpadsniper-text",
        "bonus": "stability",
        "value": "15",
        "unique": "stock",
        "verified": "?"},
      // VSS
      {
        "attachment":"quickdrawvss",
        "icon": "quickdrawsniper",
        "i18n":"quickdrawsniper",
        "name":"QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "15",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedmagvss",
        "icon": "extendedmagsniper",
        "i18n":"extendedmagsniper",
        "name":"Extended Mag for M24, AWM, SKS, VSS",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "20",
        "capacity": "20",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawvss",
        "icon": "extendedquickdrawsniper",
        "i18n":"extendedquickdrawsniper",
        "name":"Extended QuickDraw Mag for M24, AWM, SKS, VSS",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "1",
        "capacity": "24",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"cheekpadvss",
        "icon": "cheekpadsniper",
        "i18n": "cheekpadsniper",
        "name": "Cheek Pad for Sniper Rifle",
        "desc": "Reduces recoil kick and sway",
        "i18desc": "cheekpadsniper-text",
        "bonus": "stability",
        "value": "9",
        "unique": "stock",
        "verified": "?"},
      {
        "attachment":"supressorar",
        "icon": "supressorar",
        "i18n":"supressorar",
        "name":"Suppressor for AR, S12K",
        "desc": "Reduces a weaponӳ sound to increase stealth",
        "i18desc": "supressor-text",
        "unique": "muzzle",
        "verified": "?"},
      // ARS
      // AKM
      {
        "attachment":"compensatorakm",
        "icon": "compensatorar",
        "i18n":"compensatorar",
        "name":"Compensator for AR, S12K",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhiderakm",
        "icon": "flashhiderar",
        "i18n":"flashhiderar",
        "name":"Flash Hider for AR, S12K",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"quickdrawakm",
        "icon": "quickdrawar",
        "i18n":"quickdrawar",
        "name":"QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed",
        "i18desc": "quickdrawar-text",
        "bonus": "rate",
        "value": "8",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedmagakm",
        "icon": "extendedmagar",
        "i18n":"extendedmagar",
        "name":"Extended Mag for AR, S12K",
        "desc": "Increases magazine capacity",
        "bonus": "rate",
        "value": "10",
        "capacity": "40",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawakm",
        "icon": "extendedquickdrawar",
        "i18n": "extendedquickdrawar",
        "name": "Extended QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed and magazine capacity",
        "i18text ": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "16",
        "capacity ": "40",
        "unique": "mag",
        "verified": ""},
		// GROZA
      {
        "attachment":"compensatorgroza",
        "icon": "compensatorar",
        "i18n":"compensatorar",
        "name":"Compensator for AR, S12K",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhidergroza",
        "icon": "flashhiderar",
        "i18n":"flashhiderar",
        "name":"Flash Hider for AR, S12K",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"quickdrawgroza",
        "icon": "quickdrawar",
        "i18n":"quickdrawar",
        "name":"QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed",
        "i18desc": "quickdrawar-text",
        "bonus": "rate",
        "value": "8",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedmaggroza",
        "icon": "extendedmagar",
        "i18n":"extendedmagar",
        "name":"Extended Mag for AR, S12K",
        "desc": "Increases magazine capacity",
        "bonus": "rate",
        "value": "10",
        "capacity": "40",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawgroza",
        "icon": "extendedquickdrawar",
        "i18n": "extendedquickdrawar",
        "name": "Extended QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed and magazine capacity",
        "i18text ": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "16",
        "capacity ": "40",
        "unique": "mag",
        "verified": ""},
      // SCAR
      {
        "attachment":"compensatorscar",
        "icon": "compensatorar",
        "i18n":"compensatorar",
        "name":"Compensator for AR, S12K",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhiderscar",
        "icon": "flashhiderar",
        "i18n":"flashhiderar",
        "name":"Flash Hider for AR, S12K",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"verticalforegripscar",
        "icon": "verticalforegrip",
        "i18n": "verticalforegrip",
        "name": "Vertical Foregrip for M416, SCAR-L, UMP9, Vector",
        "desc": "Reduces horizontal recoil and makes switching to ADS faster.",
        "i18desc": "verticalforegrip-text",
        "bonus": "stability",
        "value": "1",
        "capacity": "40",
        "unique": "grip",
        "verified": "?"},
      {
        "attachment":"angledforegripscar",
        "icon": "angledforegrip",
        "i18n":"angledforegrip",
        "name": "Angled Foregrip for M416, SCAR-L, UMP9",
        "desc": "Slightly reduces horizontal and vertical recoil and makes switching to ADS faster.",
        "i18desc": "angledforegrip-text",
        "bonus": "stability",
        "value": "1",
        "capacity": "40",
        "unique": "grip",
        "verified": "?"},
      {
        "attachment":"quickdrawscar",
        "icon": "quickdrawar",
        "i18n":"quickdrawar",
        "name":"QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed",
        "i18desc": "quickdrawar-text",
        "bonus": "rate",
        "value": "8",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedmagscar",
        "icon": "extendedmagar",
        "i18n":"extendedmagar",
        "name":"Extended Mag for AR, S12K",
        "desc": "Increases magazine capacity",
        "bonus": "rate",
        "value": "10",
        "capacity": "40",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawscar",
        "icon": "extendedquickdrawar",
        "i18n": "extendedquickdrawar",
        "name": "Extended QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed and magazine capacity",
        "i18text ": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "16",
        "capacity ": "40",
        "unique": "mag",
        "verified": ""},
      // M16A4
      {
        "attachment":"compensatorm16a4",
        "icon": "compensatorar",
        "i18n":"compensatorar",
        "name":"Compensator for AR, S12K",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhiderm16a4",
        "icon": "flashhiderar",
        "i18n":"flashhiderar",
        "name":"Flash Hider for AR, S12K",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"quickdrawm16a4",
        "icon": "quickdrawar",
        "i18n":"quickdrawmar",
        "name":"QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "10",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedmagm16a4",
        "icon": "extendedmagar",
        "i18n":"extendedmagar",
        "name":"Extended Mag for AR, S12K",
        "desc": "Increases magazine capacity",
        "bonus": "rate",
        "value": "10",
        "capacity": "40",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawm16a4",
        "icon": "extendedquickdrawar",
        "i18n":"extendedquickdrawar",
        "name":"Extended QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "19",
        "capacity": "40",
        "unique": "mag",
        "verified": "?"},
      // M416
      {
        "attachment":"compensatorm416",
        "icon": "compensatorar",
        "i18n":"compensatorar",
        "name":"Compensator for AR, S12K",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhiderm416",
        "icon": "flashhiderar",
        "i18n":"flashhiderar",
        "name":"Flash Hider for AR, S12K",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"angledforegripm416",
        "icon": "angledforegrip",
        "i18n":"angledforegrip",
        "name": "Angled Foregrip for M416, SCAR-L, UMP9",
        "desc": "Slightly reduces horizontal and vertical recoil and makes switching to ADS faster.",
        "i18desc": "angledforegrip-text",
        "bonus": "stability",
        "value": "1",
        "capacity": "40",
        "unique": "grip",
        "verified": ""},
      {
        "attachment":"verticalforegripm416",
        "icon": "verticalforegrip",
        "i18n":"verticalforegrip",
        "name": "Vertical Foregrip for M416, SCAR-L, UMP9, Vector",
        "desc": "Vertical Foregrip for M416, SCAR-L, UMP9",
        "bonus": "stability",
        "value": "2",
        "unique": "grip",
        "verified": "?"},
      {
        "attachment":"quickdrawm416",
        "icon": "quickdrawar",
        "i18n":"quickdrawmar",
        "name":"QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "10",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedmagm416",
        "icon": "extendedmagar",
        "i18n":"extendedmagar",
        "name":"Extended Mag for AR, S12K",
        "desc": "Increases magazine capacity",
        "bonus": "rate",
        "value": "10",
        "capacity": "40",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedquickdrawm416",
        "icon": "extendedquickdrawar",
        "i18n":"extendedquickdrawar",
        "name":"Extended QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "18",
        "capacity": "40",
        "unique": "mag"},
      {
        "attachment":"tacticalstockm416",
        "icon": "tacticalstock",
        "i18n":"tacticalstock",
        "name": "Tactical Stock for M416, Vector",
        "desc": "Makes recoil recovery faster and reduces weapon sway.",
        "i18desc": "stock-text",
        "bonus": "stability",
        "value": "5",
        "unique": "stock",
        "verified": "?"},
      // SMGS
      {
        "attachment":"supressorsmg",
        "icon": "supressorsmg",
        "i18n":"supressorsmg",
        "name":"Suppressor for SMG",
        "desc": "Reduces a weaponӳ sound to increase stealth",
        "i18desc": "supressor-text",
        "unique": "muzzle",
        "verified": "?"},
      // UMP9
      {
        "attachment":"flashhiderump9",
        "icon": "flashhidersmg",
        "i18n":"flashhidersmg",
        "name":"Flash Hider for SMG",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"compensatorump9",
        "icon": "compensatorsmg",
        "i18n":"compensatorsmg",
        "name":"Compensator for SMG",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil ",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "3",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"angledforegripump9",
        "icon": "angledforegrip",
        "i18n":"angledforegrip",
        "name":"Angled Foregrip for M416, SCAR-L, UMP9",
        "desc": "Slightly reduces horizontal and vertical recoil and makes switching to ADS faster.",
        "i18desc": "angledforegrip-text",
        "bonus": "stability",
        "value": "1",
        "unique": "grip",
        "verified": "?"},
      {
        "attachment":"verticalforegripump9",
        "icon": "verticalforegrip",
        "i18n":"verticalforegrip",
        "name":"Vertical Foregrip for M416, SCAR-L, UMP9, Vector",
        "desc": "Reduces horizontal recoil and makes switching to ADS faster.",
        "i18desc": "verticalforegrip-text",
        "bonus": "stability",
        "value": "1",
        "unique": "grip",
        "verified": "?"},
      {
        "attachment":"quickdrawump9",
        "icon": "quickdrawsmg",
        "i18n":"quickdrawsmg",
        "name":"QuickDraw Mag for Micro UZI, UMP9, Vector",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "9",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedmagump9",
        "icon": "extendedmagsmg",
        "i18n":"extendedmag",
        "name":"Extended Mag for Micro UZI, UMP9, Vector",
        "desc": "Extended Mag for Micro Uzi, UMP9, Vector",
        "bonus": "rate",
        "value": "9",
        "capacity": "40",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdrawump9",
        "icon": "extendedquickdrawsmg",
        "i18n":"extendedquickdraw",
        "name":"Extended QuickDraw Mag for Micro UZI, UMP9, Vector",
        "desc": "Extended Mag for Micro Uzi, UMP9, Vector",
        "bonus": "rate",
        "value": "18",
        "capacity": "40",
        "unique": "mag",
        "verified": "?"},
      // Micro Uzi
      {
        "attachment":"compensatormicrouzi",
        "icon": "compensatorsmg",
        "i18n":"compensatorsmg",
        "name":"Compensator for SMG",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil ",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"flashhidermicrouzi",
        "icon": "flashhidersmg",
        "i18n":"flashhidersmg",
        "name":"Flash Hider for SMG",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": "?"},
      {
        "attachment":"quickdrawmicrouzi",
        "icon": "quickdrawsmg",
        "i18n":"quickdrawsmg",
        "name":"QuickDraw Mag for Micro UZI, UMP9, Vector",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "14",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedmagmicrouzi",
        "icon": "extendedmagsmg",
        "i18n":"extendedmagsmg",
        "name":"Extended Mag for Micro UZI, UMP9, Vector",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "18",
        "capacity": "35",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedquickdrawmicrouzi",
        "icon": "extendedquickdrawsmg",
        "i18n":"extendedquickdrawsmg",
        "name":"Extended QuickDraw Mag for Micro UZI, UMP9, Vector",
        "desc": "Increases reload speed and magazine capacity ",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "30",
        "capacity": "35",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"stockmicrouzi",
        "icon": "stockmicrouzi",
        "i18n":"stockmicrouzi",
        "name":"Stock for Micro UZI",
        "desc": "Makes recoil recovery faster and reduces weapon sway",
        "i18desc": "stock-text",
        "bonus": "stability",
        "value": "1",
        "unique": "stock",
        "verified": "?"},
      // VECTOR
      {
        "attachment":"compensatorvector",
        "icon": "compensatorsmg",
        "i18n":"compensatorsmg",
        "name":"Compensator for SMG",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil ",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhidervector",
        "icon": "flashhidersmg",
        "i18n":"flashhidersmg",
        "name":"Flash Hider for SMG",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"verticalforegripvector",
        "icon": "verticalforegrip",
        "i18n":"verticalforegrip",
        "name":"Vertical Foregrip for M416, SCAR-L, UMP9, Vector",
        "desc": "Reduces horizontal recoil and makes switching to ADS faster.",
        "i18desc": "verticalforegrip-text",
        "bonus": "stability",
        "value": "1",
        "capacity": "40",
        "unique": "grip",
        "verified": "?"},
      {
        "attachment":"quickdrawvector",
        "icon": "quickdrawsmg",
        "i18n":"quickdrawsmg",
        "name":"QuickDraw Mag for Micro UZI, UMP9, Vector",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "8",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedmagvector",
        "icon": "extendedmagsmg",
        "i18n":"extendedmagsmg",
        "name":"Extended Mag for Micro UZI, UMP9, Vector",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "31",
        "capacity": "25",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedquickdrawvector",
        "icon": "extendedquickdrawsmg",
        "i18n":"extendedquickdrawsmg",
        "name":"Extended QuickDraw Mag for Micro UZI, UMP9, Vector",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "38",
        "capacity": "25",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"tacticalstockvector",
        "icon": "tacticalstock",
        "i18n":"tacticalstock",
        "name": "Tactical Stock for M416, Vector",
        "desc": "Makes recoil recovery faster and reduces weapon sway.",
        "i18desc": "stock-text",
        "bonus": "stability",
        "value": "5",
        "unique": "stock",
        "verified": "?"},
      // SHOTGUNS
      // S12K
      {
        "attachment":"compensators12k",
        "icon": "compensatorar",
        "i18n":"compensatorar",
        "name":"Compensator for AR, S12K",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "2",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"flashhiders12k",
        "icon": "flashhiderar",
        "i18n":"flashhiderar",
        "name":"Flash Hider for AR, S12K",
        "desc": "Eliminates muzzle flash and slightly reduces horizontal and vertical recoil",
        "i18desc": "flashhider-text",
        "bonus": "stability",
        "value": "1",
        "unique": "muzzle",
        "verified": ""},
      {
        "attachment":"quickdraws12k",
        "icon": "quickdrawar",
        "i18n":"quickdrawmar",
        "name":"QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "10",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedmags12k",
        "icon": "extendedmagar",
        "i18n":"extendedmagar",
        "name":"Extended Mag for AR, S12K",
        "desc": "Increases magazine capacity",
        "bonus": "rate",
        "value": "10",
        "capacity": "10",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"extendedquickdraws12k",
        "icon": "extendedquickdrawar",
        "i18n":"extendedquickdrawar",
        "name":"Extended QuickDraw Mag for AR, S12K",
        "desc": "Increases reload speed and magazine capacity",
        "i18desc": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "19",
        "capacity": "10",
        "unique": "mag",
        "verified": ""},
      {
        "attachment":"choke",
        "icon": "choke",
        "i18n":"Choke",
        "name":"Choke for S1897, S686",
        "desc": "Reduces the spread of shotgun pellets.",
        "i18desc": "choke-text",
        "unique": "none",
        "verified": "?"},
      // S1897
      {
        "attachment":"bulletloopsS1897",
        "icon": "bulletloopsshotgun",
        "i18n":"bulletloopsshotgun",
        "name":"Bullet Loops for S1897, S686",
        "desc": "Increases reload speed",
        "i18desc": "bulletloops-text",
        "bonus": "rate",
        "value": "1",
        "unique": "muzzle",
        "verified": "?"},
      // S686
      {
        "attachment":"bulletloopsS686",
        "icon": "bulletloopsshotgun",
        "i18n":"bulletloopsshotgun",
        "name":"Bullet Loops for S1897, S686",
        "desc": "Increases reload speed",
        "i18desc": "bulletloops-text",
        "bonus": "rate",
        "value": "1",
        "unique": "muzzle",
        "verified": "?"},
      // P92
      {
        "attachment":"quickdrawP92",
        "icon": "quickdrawpistol",
        "i18n":"quickdrawpistol",
        "name": "QuickDraw Mag for P9, P1911, P18C",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "9",
        "capacity": "15",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedmagP92",
        "icon": "extendedmagpistol",
        "i18n":"extendedmagpistol",
        "name":"Extended Mag for P9, P1911, P18C",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "10",
        "capacity": "20",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedquickdrawP92",
        "icon": "extendedquickdrawpistol",
        "i18n":"extendedquickdrawpistol",
        "name":"Extended QuickDraw Mag for P9, P1911, P18C",
        "desc": "Increases reload speed and magazine capacity ",
        "i18desc": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "18",
        "capacity": "20",
        "unique": "mag",
        "verified": "?"},
      // P1911
      {
        "attachment":"quickdrawP1911",
        "icon": "quickdrawpistol",
        "i18n":"quickdrawpistol",
        "name": "QuickDraw Mag for P9, P1911, P18C",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "6",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedmagP1911",
        "icon": "extendedmagpistol",
        "i18n":"extendedmagpistol",
        "name":"Extended Mag for P9, P1911, P18C",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "13",
        "capacity": "12",
        "unique": "mag",
        "verified": "?"},
      {
        "attachment":"extendedquickdrawP1911",
        "icon": "extendedquickdrawpistol",
        "i18n":"extendedquickdrawpistol",
        "name":"Extended QuickDraw Mag for P9, P1911, P18C",
        "desc": "Increases reload speed and magazine capacity ",
        "i18desc": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "20",
        "capacity": "12",
        "unique": "mag",
        "verified": "?"},
		// P18C
      {
        "attachment":"quickdrawP18C",
        "icon": "quickdrawpistol",
        "i18n":"quickdrawpistol",
        "name": "QuickDraw Mag for P9, P1911, P18C",
        "desc": "Increases reload speed",
        "i18desc": "quickdraw-text",
        "bonus": "rate",
        "value": "12",
        "unique": "mag",
        "verified": "yes"},
      {
        "attachment":"extendedmagP18C",
        "icon": "extendedmagpistol",
        "i18n":"extendedmagpistol",
        "name":"Extended Mag for P9, P1911, P18C",
        "desc": "Increases magazine capacity",
        "i18desc": "extendedmag-text",
        "bonus": "rate",
        "value": "18",
        "capacity": "25",
        "unique": "mag",
        "verified": "yes"},
      {
        "attachment":"extendedquickdrawP18C",
        "icon": "extendedquickdrawpistol",
        "i18n":"extendedquickdrawpistol",
        "name":"Extended QuickDraw Mag for P9, P1911, P18C",
        "desc": "Increases reload speed and magazine capacity ",
        "i18desc": "extendedquickdraw-text",
        "bonus": "rate",
        "value": "18",
        "capacity": "25",
        "unique": "mag",
        "verified": "yes"},
      {
        "attachment":"supressorpistol",
        "icon": "supressorpistol",
        "i18n":"supressorpistol",
        "name":"Suppressor for Pistol",
        "desc": "Reduces a weapon's sound to increase stealth.",
        "i18desc": "supressorpistol-text",
        "unique": "muzzle"},
		// Crossbow
      {
        "attachment":"quiver",
        "icon": "quiver",
        "i18n":"Quiver",
        "name":"Quiver for Crossbow",
        "desc": "Increases reload speed.",
        "i18desc": "quiver-text",
        "bonus": "rate",
        "value": "1",
        "unique": "mag",
        "verified": "?"},
    ];
	
var ATTACHMENTSINFO =
	[{
        "attachment":"supressorsniper",
		"icon": "supressorsniper",
        "i18n":"supressorsniper",
        "name":"Suppressor for M24, AWM, SKS, Kar98k",
        "desc": "Reduces a weaponӳ sound to increase stealth",
        "i18desc": "supressor-text",
        "unique": "muzzle",
        "attweapons": ["m24", "awm", "sks", "kar98"]},
		{
        "attachment":"compensatorsniper",
        "icon": "compensatorsniper",
        "i18n":"compensatorsniper",
        "name":"Compensator for M24, AWM, SKS, Kar98k",
        "desc": "Slightly reduces horizontal recoil and reduces vertical recoil",
        "i18desc": "compensator-text",
        "bonus": "stability",
        "value": "3",
        "unique": "muzzle",
        "attweapons": ["m24", "awm", "sks", "kar98"]},
	]

var SIGHTS = 
    [{
      "sight":"reddot",
      "name":"Red Dot",
      "bonus": "+20.00% Faster ADS",
      "desc": "Red Dot sight for UMP9, Vector, AKM, M16A4, M416, SCAR-L, SKS, S12K, M249, Kar98k, M24, AWM, Crossbow"},
     {
       "sight":"holographic",
       "name":"Holographic",
       "desc": "Holographic sight for UMP9, Vector, AKM, M16A4, M416, SCAR-L, SKS, S12K, M249, Kar98k, M24, AWM, Crossbow"},
     {
       "sight":"scope2x",
       "name":"2x Scope",
       "desc": "2x Scope sight for UMP9, Vector, AKM, M16A4, M416, SCAR-L, SKS, S12K, M249, Kar98k, M24, AWM, Crossbow"},
     {
       "sight":"scope4x",
       "name":"4x Scope",
       "desc": "4x Scope sight for UMP9, Vector, AKM, M16A4, M416, SCAR-L, SKS, S12K, M249, Kar98k, M24, AWM, Crossbow"},
     {
       "sight":"scope8x",
       "name":"8x Scope",
       "desc": "8x Scope sight for UMP9, Vector, AKM, M16A4, M416, SCAR-L, SKS, S12K, M249, Kar98k, M24, AWM, Crossbow"},
     {
       "sight":"scope15x",
       "name":"15x Scope",
       "desc": "15x Scope sight for UMP9, Vector, AKM, M16A4, M416, SCAR-L, SKS, S12K, M249, Kar98k, M24, AWM, Crossbow"},
    ];

var PUBGCLOTHES =
    [{
      "item":"dirtytanktop-white",
      "name": "Dirty Tank-top (White)",
      "bp": "20"},
     {
       "item":"tshirt-red",
       "name": "T-shirt (Red)",
       "bp": "20"},
     {
       "item":"combatpants-white",
       "name": "Combat Pants (White)",
       "bp": "30"},
     {
       "item":"bloodyshirt",
       "name": "Bloody Shirt",
       "bp": "30"},
     {
       "item":"workingboots",
       "name": "Working Boots",
       "bp": "30"},
     {
       "item":"baseballcap",
       "name": "Baseball cap",
       "bp": "50"},
     {
       "item":"longsleevedtshirt-lightblue",
       "name": "Long Sleeved T-shirt (Light Blue)",
       "bp": "50"},
     {
       "item":"dirtytanktop-grey",
       "name": "Dirty Tank-top (Grey)",
       "bp": "20"},
     {
       "item":"combatpants-blue",
       "name": "Combat Pants (Blue)",
       "bp": "30"},
     {
       "item":"combatpants-camo",
       "name": "Combat Pants (camo)",
       "bp": "30"},
     {
       "item":"bloodytanktop-white",
       "name": "Bloody Tank-top (White)",
       "bp": "20"},
     {
       "item":"longsleevedtshirt-striped",
       "name": "Long Sleeved T-shirt (Striped)",
       "bp": "50"},
     {
       "item":"longsleevedtshirt-black",
       "name": "Long Sleeved T-shirt (Black)",
       "bp": "50"},
     {
       "item":"shirt-white",
       "name": "Shirt (White)",
       "bp": "30"},
     {
       "item":"greyboots",
       "name": "Grey Boots",
       "bp": "30"},
     {
       "item":"fingerlessgloves-tan",
       "name": "Fingerless Gloves (Tan)",
       "bp": "30"},
     {
       "item":"vintagebaseballhat-white",
       "name": "Vintage Baseball Hat (White)",
       "bp": "50"},
     {
       "item":"boots-punk",
       "name": "Boots (Punk)",
       "bp": "50"},
     {
       "item":"fingerlessgloves-leather",
       "name": "Fingerless Gloves (Leather)",
       "bp": "30"},
     {
       "item":"tanktop-charcoal",
       "name": "Tank-top (Charcoal)",
       "bp": "20"},
     {
       "item":"combatpants-greycamo",
       "name": "Combat Pants (Grey Camo)",
       "bp": "30"},
     {
       "item":"rimless-sunglasses",
       "name": "Rimless Sunglasses",
       "bp": "100"},
     {
       "item":"glasses-punk",
       "name": "Glasses (Punk)",
       "bp": "50"},
     {
       "item":"gasmask-half",
       "name": "Gas Mask (Half)",
       "bp": "50"},
     {
       "item":"paddedjacket-khaki",
       "name": "Padded Jacket (khaki)",
       "bp": "150"},
     {
       "item":"sunglasses",
       "name": "Sunglasses",
       "bp": "100"},
     {
       "item":"paddedjacket-beige",
       "name": "Padded Jacket (Beige)",
       "bp": "150"},
     {
       "item":"shirt-black",
       "name": "Shirt (Black)",
       "bp": "30"},
     {
       "item":"gasmask",
       "name": "Gas Mask",
       "bp": "30"},
     {
       "item":"paddedjacket-grey",
       "name": "Padded Jacket (GREY)",
       "bp": "150"},
     {
       "item":"paddedjacket-purple",
       "name": "Padded Jacket (Purple)",
       "bp": "150"},
     {
       "item":"paddedjacket-urban",
       "name": "Padded Jacket (Urban)",
       "bp": "150"},
     {
       "item":"paddedjacket-camo",
       "name": "Padded Jacket (Camo)",
       "bp": "150"},
     {
       "item":"grey-shirt",
       "name": "Grey Shirt",
       "bp": ""},
     {
       "item":"jeans-tan",
       "name": "Jeans (Tan)",
       "bp": ""},
     {
       "item":"red-hitoptrainers",
       "name": "Red Hi-top Trainers",
       "bp": ""},
     {
       "item":"pu-bandana",
       "name": "PLAYERUNKNOWN's Bandana",
       "bp": ""},
     {
       "item":"pu-trenchcoat",
       "name": "PLAYERUNKNOWN'S Trenchcoat",
       "bp": ""},
     {
       "item":"pu-set",
       "name": "PLAYERUNKNOWN SET",
       "bp": ""},
     {
       "item":"twitchprimeshirt",
       "name": "Twitch Prime Shirt",
       "bp": ""},
     {
       "item":"twitchprimeboots",
       "name": "Twitch Prime Boots",
       "bp": ""},
     {
       "item":"twitchprimecombatpants",
       "name": "Twitch Prime Combat Pants",
       "bp": ""},
     {
       "item":"twitchprimebalaclava",
       "name": "Twitch Prime Balaclava",
       "bp": ""},
    ];

var PUBGCARS =
    [
    ];























